os: linux
dist: bionic

language: ruby
rvm: 2.6.5

before_install:
  - pyenv global 3.7.6

install:
  - pip install -r _scripts/py/requirements.txt
  - bundle install --path vendor/bundle --quiet

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL error (for htmlproofer)

script:
  - >-
    git clone https://${GH_PAT}@github.com/${GH_USER}/${BUILDER_REPO}.git
    ${HOME}/${BUILDER_REPO} --depth=1 -q
  - cp -r ${HOME}/${BUILDER_REPO}/framework/* .
  - bash _cibuild.sh

branches:
  only: stable

git:
  depth: false # for posts lastmod

cache:
  directories:
    - $TRAVIS_BUILD_DIR/vendor/bundle

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer 

notifications:
  email:
    recipients:
      - fatihsvk1@gmail.com
    on_success: never
    on_failure: always


# Upload Jekyll blog files to Amazon S3 bucket
deploy:
  on:
    branch: master
  provider: s3
  bucket: fsoftdev.com 
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: eu-west-1
  acl: public_read
  skip_cleanup: true
  local_dir: ./_site