os: linux
dist: bionic

language: ruby
rvm: 2.6.5

install:
  - bundle install

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL error (for htmlproofer)

branches:
  only: master


cache:
  directories:
    - $TRAVIS_BUILD_DIR/vendor/bundle


env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
notifications:
  email:
    recipients:
      - fatihsvk1@gmail.com
    on_success: never
    on_failure: always


# Upload Jekyll blog files to Amazon S3 bucket
deploy:
  on:
    branch: master
  provider: s3
  bucket: fsoftdev.com 
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: eu-west-1
  acl: public_read
  skip_cleanup: true
  local_dir: ./_site