
language: ruby
rvm: 2.6.5


# Install Jekyll
install:
  - gem install jekyll

# Build Jekyll blog
script:
  - jekyll build


addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL error (for htmlproofer)

branches:
  only: master

git:
  depth: false # for posts lastmod


# Upload Jekyll blog files to Amazon S3 bucket
deploy:
  on:
    branch: master
  provider: s3
  bucket: fsoftdev.com 
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: eu-west-1
  acl: public_read
  skip_cleanup: true
  local_dir: ./_site