os: linux
dist: bionic

language: ruby
rvm: 2.6.5

# Install Jekyll
install:
  - gem install jekyll

# Build Jekyll blog
script:
  - jekyll build
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer 

notifications:
  email:
    recipients:
      - fatihsvk1@gmail.com
    on_success: never
    on_failure: always


# Upload Jekyll blog files to Amazon S3 bucket
deploy:
  provider: s3
  bucket: fsoftdev.com 
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: eu-west-1
  acl: public_read
  skip_cleanup: true
  local_dir: ./_site